services:

  cloud-agent:
    container_name: cloud-agent
    image: index.docker.io/sourcegraph/src-tunnel-agent:latest@sha256:9b7a911d189165df66217f330f9581c2bb546596b24adec8e25654d84a1e0b73
    volumes:
      - ../config/cloud-agent-service-account-key.json:/sourcegraph/cloud-agent-service-account-key.json:ro
      - ../config/cloud-agent-config.yaml:/sourcegraph/cloud-agent-config.yaml:ro
    command: ["-config=/sourcegraph/cloud-agent-config.yaml"]
    restart: always
    networks:
      - default

  src-serve-git:
    # Uses a valid hostname as container_name, to trick the cloud agent and code host config into finding this container on the Docker network
    container_name: src-serve-git-ubuntu.local
    image:  index.docker.io/sourcegraph/src-cli:latest@sha256:c7225a3a895fee19816fbde65a50572a0a5ea59129b6dfa59a2d166ac1292e99
    volumes:
      - ../../../sg/src-serve-root/:/sourcegraph/src-serve-root:ro
    command: "serve-git -addr :443 /sourcegraph/src-serve-root"
    restart: always
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.20.2.0/27"
