# Levels of settings
  # Env vars
  # repos-to-convert.yaml
    # Global
    # Server
    # Repo

global:
  # Global configs for all repos, applies to all repos of all types
  bare-clone: true
  git-default-branch: main
  default-branch-only: false
  # Global configs for each repo type, applies to all repos of each types
  svn:
    svn-layout: standard
  tfvc:
    username: user
  git:
    git-clone-command-args: --depth 1000000

# List of servers, with their server config, and list of repos

asf:
  type: svn
  code-host-name: svn.apache.org
  commits-to-skip:
    - "1"
    - "2"
  fetch-batch-size: 100
  fetch-interval: 60
  git-org-name: asf
  max-concurrent-conversions: 20
  password: password1
  repo-parent-url: https://svn.apache.org/repos/asf/
  svn-layout: standard
  username: username
  repos:
    - allura:
        bare-clone: false
        branches:
          - main
          - dev
        code-host-name: test.org
        commits-to-skip:
          - "3"
          - "4"
        fetch-batch-size: 2
        fetch-interval: 600
        git-default-branch: dev
        git-ignore-file-path: ""
        git-org-name: test
        git-repo-name: allura-destination
        source-repo-name: allura
        svn-layout:
          trunk: trunk-dir-path
          branches:
            - branch-dir-path-one
            - branch-dir-path-two
          tags:
            - tags-dir-path-one
            - tags-dir-path-two
        username: allura-username
        password: allura-password
    - ambari
    - ant
    - apr
    - beam
    - board
    - bugs
    - cocoon
    - comdev
    - commons
    - crunch:
        svn-repo-code-root: site
    - curator:
        svn-repo-code-root: site
    - datafu:
        svn-repo-code-root: site
    - db
    - eagle
    - falcon
    - fundraising
    - httpcomponents
    - httpd
    - infrastructure
    - jackrabbit
    - johnzon
    - karaf
    - knox
    - kylin
    - lens
    - lucene

msf:
  type: svn
  bare-clone: false
  code-host-name: svn.apache.org
  default-branch-only: false
  fetch-batch-size: 10
  fetch-interval: 200
  git-org-name: asf
  max-concurrent-conversions: 10
  password: password2
  repo-parent-url: https://svn.apache.org/repos/asf/
  svn-layout: standard
  username: username
  repos:
    - manifoldcf
    - maven
    - openoffice
    - parquet:
        svn-repo-code-root: site
    - pdfbox
    - perl
    - phoenix
    - poi
    - reef:
        svn-repo-code-root: site
    - spamassassin
    - subversion
    - tomcat
    - twill
    - uima
    - xerces
    - xml-beans
    - xmlbeans
    - zest:
        svn-repo-code-root: site

azure-tfvc:
  type: tfvc
  repos:
    - tfvc-project-1:
        tfvc-collection: https://dev.azure.com/example/DefaultCollection
        git-org-name: example
        git-repo-name: tfvc-project-1
        git-default-branch: dev
        branches:
          dev: $/tfvc-project-1/app/main/dev
          release-v1: $/tfvc-project-1/app/main/release-v1
          release-v2: $/tfvc-project-1/app/main/release-v2
          release-v4: $/tfvc-project-1/app/main/release-v4

azure-git: # Both Git and TFVC on the same server, need to provide different server name keys
  type: azure

gitolite:
  type: git
  code-host-name: git.example.com
  git-ssh-command-args: -i /sg/.ssh/id_rsa -o HostKeyAlgorithms=ssh-rsa -o PubkeyAcceptedKeyTypes=ssh-rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  repos:
    - repo-main:
        repo-url: ssh://git@git.example.com/repo.git
        git-org-name: org
        git-repo-name: repo-main
        git-default-branch: main
    - repo-dev:
        repo-url: ssh://git@git.example.com/repo.git
        git-org-name: org
        git-repo-name: repo-dev
        git-default-branch: dev
