# Overrides for customer1

# See Docker Compose docs for why a separate override file is required
# https://docs.docker.com/compose/how-tos/multiple-compose-files/include/#include-and-overrides

services:

  repo-converter:
    image: ghcr.io/sourcegraph/repo-converter:marc-fixes
    environment:
      - LOG_LEVEL=DEBUG
      - REPO_CONVERTER_INTERVAL_SECONDS=60
      - TRUNCATED_OUTPUT_MAX_LINES=40
    user: ${CURRENT_UID_GID}
    volumes:
      - ../../../../src-serve-root/:/sg/src-serve-root
      - ../../../config/repos-to-convert.yaml:/sg/repos-to-convert.yaml:ro
      - ../../../dev/toprc:/root/.config/procps/toprc

  src-serve-git:
    container_name: src-serve-git-ubuntu.local
    user: ${CURRENT_UID_GID}
    volumes:
      - ../../../../src-serve-root/:/sg/src-serve-root:ro

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.20.2.0/27"
