# Overrides for customer1

# See Docker Compose docs for why a separate override file is required
# https://docs.docker.com/compose/how-tos/multiple-compose-files/include/#include-and-overrides

services:

  repo-converter:
    image: ghcr.io/sourcegraph/repo-converter:latest
    environment:
      - LOG_LEVEL=DEBUG
      - REPO_CONVERTER_INTERVAL_SECONDS=600
      - TRUNCATED_OUTPUT_MAX_LINES=20
    # It seems like the only way this works for both Podman and Docker Compose,
    # is to run the container as UID=10001 and GID 10002,
    # both on the host,
    # and inside the container
    user: ${CURRENT_UID_GID}
    volumes:
      - ../../dev/toprc:/home/sourcegraph/.config/procps/toprc

  src-serve-git:
    container_name: src-serve-git-ubuntu.local
    user: ${CURRENT_UID_GID}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.20.2.0/27"
