apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: repo-converter
  labels:
    app.kubernetes.io/component: repo-converter
    app: repo-converter
    deploy: sourcegraph
  name: repo-converter

spec:
  serviceName: "repo-converter"
  replicas: 1
  selector:
    matchLabels:
      app: repo-converter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: repo-converter
        app: repo-converter
        deploy: sourcegraph
    spec:
      containers:
      - name: repo-converter
        image: ghcr.io/sourcegraph/repo-converter:v0.5.2
        # env:
        # - name: REPO_CONVERTER_INTERVAL_SECONDS
        #   value: "60" # Default 3600
        # - name: LOG_LEVEL
        #   value: "DEBUG" # DEBUG INFO WARNING ERROR CRITICAL # Default INFO
        volumeMounts:
        - name: src-serve-root
          mountPath: /sg/src-serve-root
        - name: repos-to-convert
          mountPath: /sg/config/repos-to-convert.yaml
          readOnly: true
      - name: src-serve-git
        image:  index.docker.io/sourcegraph/src-cli:latest
        command: ["src", "serve-git", "-addr", ":3434", "/sg/src-serve-root"]
        ports:
        - containerPort: 3434
        volumeMounts:
        - name: src-serve-root
          mountPath: /sg/src-serve-root
      volumes:
      - name: repos-to-convert
        secret:
          secretName: repos-to-convert-secret
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/component: repo-converter
        app: repo-converter
        deploy: sourcegraph
      name: src-serve-root
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Gi  # Adjust size as needed
