apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: repo-converter
    app: repo-converter
    deploy: sourcegraph
  name: repos-to-convert-secret
type: Opaque
stringData:
  repos-to-convert.yaml: |
    # Content of repos-to-convert.yaml
    allura:
      type: SVN
      svn-repo-code-root: https://svn.apache.org/repos/asf/allura
      code-host-name: svn.apache.org
      git-org-name: asf
    ambari:
      type: SVN
      svn-repo-code-root: https://svn.apache.org/repos/asf/ambari
      code-host-name: svn.apache.org
      git-org-name: asf
      layout: standard
    ant:
      type: SVN
      svn-repo-code-root: https://svn.apache.org/repos/asf/ant
      code-host-name: svn.apache.org
      git-org-name: asf
