# Sane defaults, which will work as is
# Can create a docker-compose.override.yaml file to override any of these defaults

services:

  cloud-agent:
    command: ["-config=/sg/config/config.yaml"]
    container_name: cloud-agent
    image: index.docker.io/sourcegraph/src-tunnel-agent:latest
    networks:
      - default
    restart: always
    volumes:
      - ../../config/cloud-agent/:/sg/config:ro

  repo-converter:
    container_name: repo-converter
    image: ghcr.io/sourcegraph/repo-converter:v0.5.1
    # environment:
      # - REPO_CONVERTER_INTERVAL_SECONDS=60 # Default is 3600 seconds (1 hour)
      # - LOG_LEVEL=DEBUG # DEBUG INFO WARNING ERROR CRITICAL # Default is INFO
    restart: always
    volumes:
      - ../../config/repo-converter:/sg/config:ro
      - ../../../src-serve-root/:/sg/src-serve-root

  src-serve-git:
    command: "serve-git -addr :443 /sg/src-serve-root"
    # Uses a valid hostname as container_name, to trick the cloud agent and code host config into finding this container on the Docker network
    container_name: src-serve-git.local
    image:  index.docker.io/sourcegraph/src-cli:latest
    networks:
      - default
    restart: always
    volumes:
      - ../../../src-serve-root/:/sg/src-serve-root:ro

networks:
  default:
