# Sane defaults, which will work as is
# Can create a docker-compose.override.yaml file to override any of these defaults

services:

  cloud-agent:
    container_name: cloud-agent
    image: index.docker.io/sourcegraph/src-tunnel-agent:latest
    volumes:
      - ../../config/cloud-agent-service-account-key.json:/sourcegraph/cloud-agent-service-account-key.json:ro
      - ../../config/cloud-agent-config.yaml:/sourcegraph/cloud-agent-config.yaml:ro
    command: ["-config=/sourcegraph/cloud-agent-config.yaml"]
    restart: always
    networks:
      - default

  repo-converter:
    container_name: repo-converter
    image: ghcr.io/sourcegraph/implementation-bridge-repo-converter:latest
    volumes:
      - ../../config/repos-to-convert.yaml:/sourcegraph/repos-to-convert.yaml:ro
      - ../../src-serve-root/:/sourcegraph/src-serve-root
    restart: always
    # environment:
      # - REPO_CONVERTER_INTERVAL_SECONDS=60 # Default is 3600 seconds (1 hour)
      # - LOG_LEVEL=DEBUG # DEBUG INFO WARNING ERROR CRITICAL # Default is INFO

  src-serve-git:
    # Uses a valid hostname as container_name, to trick the cloud agent and code host config into finding this container on the Docker network
    container_name: src-serve-git.local
    image:  index.docker.io/sourcegraph/src-cli:latest
    volumes:
      - ../../src-serve-root/:/sourcegraph/src-serve-root:ro
    command: "serve-git -addr :443 /sourcegraph/src-serve-root"
    restart: always
    networks:
      - default

networks:
  default:
