name: Cleanup old Docker Images from GitHub Container Registry

on:
  workflow_dispatch: # Creates button in web UI to run the workflow manually, shouldn't be needed
  # schedule:
  #   - cron: '0 0 * * 0' # Run on Sundays at 00:00 UTC every week

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:

      - name: Clean up old images for implementation-bridge-repo-converter
        uses: actions/delete-package-versions@v5
        with:
          # delete-only-untagged-versions: 'true'
          ignore-versions: '([v]?\d+\.\d+\.\d+|latest|main)'
          min-versions-to-keep: 10
          package-name: implementation-bridge-repo-converter
          package-type: container

      # - name: Clean up old images for repo-converter
      #   uses: actions/delete-package-versions@v5
      #   with:
      #     delete-only-untagged-versions: 'true'
      #     # ignore-versions: '([v]?\d+\.\d+\.\d+|latest)'
      #     min-versions-to-keep: 100
      #     package-name: implementation-bridge-repo-converter
      #     package-type: container

      # - name: Clean up old images for repo-converter/podman-build-cache
      #   uses: actions/delete-package-versions@v5
      #   with:
      #     delete-only-untagged-versions: 'true'
      #     # ignore-versions: '([v]?\d+\.\d+\.\d+|latest)'
      #     min-versions-to-keep: 100
      #     package-name: implementation-bridge-repo-converter
      #     package-type: container