name: Cleanup old Docker Images from GitHub Container Registry

on:
  workflow_dispatch: # Creates button in web UI to run the workflow manually, shouldn't be needed
    inputs:
      package-name:
        type: string
        description: Package name
        default: implementation-bridge-repo-converter
        required: true

  # schedule:
  #   - cron: '0 0 * * 0' # Run on Sundays at 00:00 UTC every week

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:

      - name: Cleanup package versions
        uses: actions/delete-package-versions@v5
        with:
          delete-only-untagged-versions: true
          min-versions-to-keep: 2
          package-name: ${{ github.event.inputs.package-name }}
          package-type: container
