name: Podman build and push to GitHub Container Registry

# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

on:
  pull_request:
    branches:
      - "**"
      - "!**renovate**"
    paths:
      - ".github/**"
      - "build/**"
      - "src/**"
    types:
      - opened
      - reopened
      - edited
  push:
    branches:
      - "**"
      - "!**renovate*"
    paths:
      - ".github/**"
      - "build/**"
      - "src/**"
    tags:
      - "**"
  # Creates button in web UI to run the workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Log in to GitHub Container Registry
        run:  echo "${{ secrets.GITHUB_TOKEN }}" | podman login -u "${{ github.repository_owner }}" --password-stdin ghcr.io

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push images
        run:  bash .github/workflows/build.sh
