name: Podman build and push to GitHub Container Registry

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_dispatch: # Creates button in web UI to run the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Log in to GitHub Container Registry
        run:  echo "${{ secrets.GITHUB_TOKEN }}" | podman login -u "${{ github.repository_owner }}" --password-stdin ghcr.io

      - name: Checkout repository
        uses: actions/checkout@v4

        # https://github.com/actions/cache/blob/main/examples.md#using-pip-to-get-cache-location
      - name: Get pip cache dir
        id: pip-cache
        shell: bash
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: pip cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build and push images
        run:  bash .github/workflows/build.sh
