name: Podman build and push to GitHub Container Registry

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_dispatch: # Creates button in web UI to run the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Log in to GitHub Container Registry
        run:  echo "${{ secrets.GITHUB_TOKEN }}" | podman login -u "${{ github.repository_owner }}" --password-stdin ghcr.io

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push images
        run:  bash .github/workflows/build.sh
