name: Podman build and push to GitHub Container Registry

on:
  workflow_dispatch: # Creates button in web UI to run the workflow manually
  push: # All pushes
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login -u "${{ github.repository_owner }}" --password-stdin ghcr.io

      - name: Build and push image
        run: |
          podman build -f build/Dockerfile --format docker --platform linux/amd64 -t ghcr.io/sourcegraph/repo-converter:latest .
          podman push ghcr.io/sourcegraph/repo-converter:latest
