name: Podman build and push to GitHub Container Registry

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_dispatch: # Creates button in web UI to run the workflow manually


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set env vars
        run: |
          export BUILD_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          export BUILD_COMMIT="$(git rev-parse --short HEAD)"
          export BUILD_DIRTY="$(git diff --quiet && echo 'False' || echo 'True')"
          export BUILD_DATE="$(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          export BUILD_DATE_TAG="$(date -u +'%Y-%m-%d-%H-%M-%S')"
          export BUILD_TAG="$(git tag --points-at HEAD)"
          export ENV_FILE="build/.env"
          {
              echo "BUILD_BRANCH=${BUILD_BRANCH}"
              echo "BUILD_COMMIT=${BUILD_COMMIT}"
              echo "BUILD_DATE=${BUILD_DATE}"
              echo "BUILD_DIRTY=${BUILD_DIRTY}"
              echo "BUILD_TAG=${BUILD_TAG}"
          } > "${ENV_FILE}"

      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login -u "${{ github.repository_owner }}" --password-stdin ghcr.io

      - name: Build and push image
        run: |
          podman build \
            -f build/Dockerfile \
            --format docker \
            --platform linux/amd64 \
            -t repo-converter \
            .
          podman push repo-converter ghcr.io/sourcegraph/repo-converter:latest
          export BUILD_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "BUILD_BRANCH=${BUILD_BRANCH}"
          podman push repo-converter ghcr.io/sourcegraph/repo-converter:${BUILD_BRANCH}
          export BUILD_COMMIT="$(git rev-parse --short HEAD)"
          echo "BUILD_COMMIT=${BUILD_COMMIT}"
          podman push repo-converter ghcr.io/sourcegraph/repo-converter:${BUILD_COMMIT}
          export BUILD_DATE_TAG="$(date -u +'%Y-%m-%d-%H-%M-%S')"
          echo "BUILD_DATE_TAG=${BUILD_DATE_TAG}"
          podman push repo-converter ghcr.io/sourcegraph/repo-converter:${BUILD_DATE_TAG}
